runtime: nodejs20
env: standard
service: frontend

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
# Optional: Set environment variables
# env_variables:
#   NODE_ENV: 'production'

# Optional: Set instance class and scaling
# instance_class: F2
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 3