runtime: nodejs20
env: standard
service: frontend

handlers:
  - url: /(.*\.(js|css|png|jpg|ico|json|txt|svg|woff2?))$
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|ico|json|txt|svg|woff2?))$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
# Optional: Set environment variables
# env_variables:
#   NODE_ENV: 'production'

# Optional: Set instance class and scaling
# instance_class: F2
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 3