
runtime: nodejs20
env: standard
service: frontend

handlers:
- url: /(.*\.(js|css|png|jpg|ico|json|txt|svg|woff2?))$
  static_files: build/\1
  upload: build/(.*\.(js|css|png|jpg|ico|json|txt|svg|woff2?))$
  secure: always
  login: required

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  login: required
